language: php

php:
  - 7.1
  - 7.2

install:
  - composer selfupdate
  - composer install
  - composer run-script travis-build-env

script:
  - ./vendor/bin/phpcs -s
  - ./vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
