language: php

php:
  - 7.1
  - 7.2

install:
  - composer selfupdate
  - composer install --no-interaction
  - composer run-script travis-build-env

env:
  - APP_ENV="dev"

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS framework;'

script:
  - ./vendor/bin/phinx migrate
  - ./vendor/bin/phinx seed:run
  - ./vendor/bin/php-cs-fixer fix . --dry-run
  - ./vendor/bin/phpunit
